### ISSUE TITLE
VNE voice warning doesn't stop

### ISSUE THREAD

**Issue by bitwisetech** [TheFGFSEagle/pilatus-pc6-family#3]
After exceeding VNE the audio message: "VNE Exceeded"  beomes continual.  The 'Stall Warning' beep properly shuts off after the condition is corrected. Tks  !

**Comment by magnetic-eagle** [comment]
Thanks for reporting - this is caused by the VNE Exceeded warning being repeated at frame rate, but the voice can't keep up with that, so it continues playing for a long time after you went back below Vne - will push a fix right now ! :)

**Comment by magnetic-eagle** [comment]
Fixed ! :)
